### ISSUE TITLE
Logging deployment to router

### ISSUE THREAD

**Issue by ekrichbaum** [peering-manager/peering-manager#565] opened 2022-03-15 23:49 UTC
### Peering Manager version

v1.6.0

### Feature type

New functionality

### Proposed functionality

User action of a config push does not log. I would propose that going to devices, routers, {router}, configuration and hitting Deploy manually should log to the change log similar to updating an object in the db.

### Use case

Basic logging of user based action.

**Comment by gmazoyer** [comment] 2022-04-30 09:29
These actions are already logged as job results, also allowing to have more details about what happened during the process (duration, completion status, steps taken and output).

I think it would be a duplicate of info of logging this into the regular changelog, which is also not suited for this kind of logging at this time.

However we should give more visibility about jobs that have run for a router by adding a new tab, next to the changelog one, in the router views.

**Closed** 2022-08-21 04:32 UTC
Labels: type: enhancement, type: gathering feedback, priority: low, pending closure
