### ISSUE TITLE
Maintenance Notifications

### ISSUE THREAD

**Issue by jaakub** [peering-manager/peering-manager#363] opened 2021-02-28 17:12 UTC
### Environment
* Python version:  3.8.5
* Peering Manager version:  1.3.3-dev

### Proposed Functionality

Allow issuing of bulk maintenance notification (based on an e-mail template) to all sessions on a particular device when set to maintenance mode.  This might require a few additional fields under the device page right next to `Device state` which would allow us to set a maintenance window date, start and finish time.

### Use Case

Useful when the device is scheduled for maintenance and all peering partners/customers need to be notified of that maintenance taking place in advance.  At the moment, this is not possible but would be extremely useful (at least I'm not aware of it).

**Comment by nido009** [comment] 2021-02-28 17:57
might also need a maintainance-contact within an AS. But Great Idea 👍

**Comment by jaakub** [comment] 2021-02-28 18:13
> might also need a maintainance-contact within an AS. But Great Idea 👍 

Indeed, I think a sensible approach to it might be to have to select that maintenance-contact manually from imported peering-db contacts, or maybe a free text field.

**Comment by gmazoyer** [comment] 2021-04-25 12:45
Mention #240

**Comment by jamesditrapani** [comment] 2021-04-28 12:08
@jaakub Going to close this as its a duplicate of #240.

**Closed by jamesditrapani** 2021-04-28 12:08 UTC
Labels: type: feature request
