### ISSUE TITLE
Jinja session policy filters don't restrict by IP family

### ISSUE THREAD

**Issue by mngan** [peering-manager/peering-manager#449] opened 2021-06-17 22:09 UTC
### Environment

* Python version:  3.8
* Peering Manager version:  1.4.2

### Steps to Reproduce

1. Add an IPv4 export policy to a BGP Group
2. Add an IPv6 export policy to a BGP Group
3. Add a universal export policy to a BGP Group
3. Create a IPv4 session in the BGP Group
4. Render router template with `session | merge_export_policies`

### Expected Behavior
You should have an export policy list with just the IPv4 and universal policy
```
neighbor 1.1.1.1 {
  ...
  export [ ipv4-policy universal-policy ];
  ...
}
```

### Observed Behavior
However,  the IPv6 export policy also ends up in the export policy list

```
neighbor 1.1.1.1 {
  ...
  export [ ipv4-policy ipv6-policy universal-policy ];
  ...
}
```

**Comment by mngan** [comment] 2021-06-17 22:13
Submitted PR #450

**Comment by jamesditrapani** [comment] 2021-06-17 22:23
@mngan This has already been resolved in b5b097842cb8ccf0281bd03003167c0ea240169e. However, the additions you have made do make it look cleaner.

**Comment by mngan** [comment] 2021-06-17 22:25
You guys are too fast for me :)

**Comment by jamesditrapani** [comment] 2021-06-17 22:29
@gmazoyer Is too fast for everyone :)

For the sake of reducing the amount of duplicate code I am still happy to merge this.. will let Guill give the final approve/deny.

**Comment by gmazoyer** [comment] 2021-06-18 10:12
Duplicate of #448

**Closed** 2021-06-18 20:34 UTC
Labels: status: duplicate
